name: Android CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Repoyu checkout et
      - uses: actions/checkout@v4

      # 2. Java'yı kur
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. GRADLE WRAPPER KURULUMU (EKLED
