name: Android CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      # Android kurulumu için alternatif resmi eylem
      - uses: android-actions/setup-android@v2  # v4 yerine v2 (son stabil sürüm)
        # VEYA Google'un resmi eylemi:
        # - uses: android-github-actions/setup-android@v2

      - run: chmod +x gradlew
      - run: ./gradlew assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: WebWatchPlus-APK
          path: app/build/outputs/apk/debug/*.apk
